import type { Metadata } from 'next';
import './globals.css';
import ReduxProvider from '@/Provider/ReduxProvider';
import Header from './ui/header';
import fontObject from './ui/fonts/fonts';

export const metadata: Metadata = {
  title: '나만의 갤러리',
  description: 'Generated by create next app',
};

const { inter } = fontObject;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body className={`${inter.className} antialiased`}>
        <ReduxProvider>
          <Header />
          <main>{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
